// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: G.Gobang.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct G_Gobang_GobangData: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".GobangData"

  /// 信息类型  1进入房间，2离开房间，3准备,4开始，5悔棋，6同意悔棋,100下棋
  var type: UInt32 = 0

  ///  1.黑子  2.白子
  var subtype: UInt32 = 0

  /// 房间id
  var roomID: UInt32 = 0

  /// 消息发送方
  var from: String = String()

  /// 消息接受方
  var to: String = String()

  /// 棋盘 x轴
  var x: UInt32 = 0

  /// 棋盘 y轴
  var y: UInt32 = 0

  /// 消息接受方
  var msg: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self.type)
      case 2: try decoder.decodeSingularUInt32Field(value: &self.subtype)
      case 3: try decoder.decodeSingularUInt32Field(value: &self.roomID)
      case 4: try decoder.decodeSingularStringField(value: &self.from)
      case 5: try decoder.decodeSingularStringField(value: &self.to)
      case 6: try decoder.decodeSingularUInt32Field(value: &self.x)
      case 7: try decoder.decodeSingularUInt32Field(value: &self.y)
      case 8: try decoder.decodeSingularStringField(value: &self.msg)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != 0 {
      try visitor.visitSingularUInt32Field(value: self.type, fieldNumber: 1)
    }
    if self.subtype != 0 {
      try visitor.visitSingularUInt32Field(value: self.subtype, fieldNumber: 2)
    }
    if self.roomID != 0 {
      try visitor.visitSingularUInt32Field(value: self.roomID, fieldNumber: 3)
    }
    if !self.from.isEmpty {
      try visitor.visitSingularStringField(value: self.from, fieldNumber: 4)
    }
    if !self.to.isEmpty {
      try visitor.visitSingularStringField(value: self.to, fieldNumber: 5)
    }
    if self.x != 0 {
      try visitor.visitSingularUInt32Field(value: self.x, fieldNumber: 6)
    }
    if self.y != 0 {
      try visitor.visitSingularUInt32Field(value: self.y, fieldNumber: 7)
    }
    if !self.msg.isEmpty {
      try visitor.visitSingularStringField(value: self.msg, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

struct G_Gobang_GobangAck: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".GobangAck"

  /// 0:发送成功，msg_id有效；1+：发送失败;
  var errCode: String = String()

  /// 错误消息
  var errMsg: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.errCode)
      case 2: try decoder.decodeSingularStringField(value: &self.errMsg)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.errCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errCode, fieldNumber: 1)
    }
    if !self.errMsg.isEmpty {
      try visitor.visitSingularStringField(value: self.errMsg, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "G.Gobang"

extension G_Gobang_GobangData: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "subtype"),
    3: .standard(proto: "room_id"),
    4: .same(proto: "from"),
    5: .same(proto: "to"),
    6: .same(proto: "x"),
    7: .same(proto: "y"),
    8: .same(proto: "msg"),
  ]

  func _protobuf_generated_isEqualTo(other: G_Gobang_GobangData) -> Bool {
    if self.type != other.type {return false}
    if self.subtype != other.subtype {return false}
    if self.roomID != other.roomID {return false}
    if self.from != other.from {return false}
    if self.to != other.to {return false}
    if self.x != other.x {return false}
    if self.y != other.y {return false}
    if self.msg != other.msg {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension G_Gobang_GobangAck: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "err_code"),
    2: .standard(proto: "err_msg"),
  ]

  func _protobuf_generated_isEqualTo(other: G_Gobang_GobangAck) -> Bool {
    if self.errCode != other.errCode {return false}
    if self.errMsg != other.errMsg {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
